services:
  localstack:
    container_name: dynamodb
    image: localstack/localstack:0.12.13
    environment:
      - SERVICES=dynamodb
    ports:
      - "4566:4566"
    depends_on:
      - dynamodb-admin
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
    ports:
      - "8001:8001"
