spring:
  application.name: @project.name@

server:
  port: 9000

logging:
  file.name: immutables-dynamodb-mapper-poc.log
  level:
    com.github.simy4.poc: DEBUG
    org.springframework: WARN

springdoc.swagger-ui.path: /

management.server.port: 9001

db.entities.table-name: ${ENTITIES_TABLE:entities-table}

---
spring.config.activate.on-profile: local
