spring:
  application.name: @project.name@

server:
  port: 9000

logging:
  file.name: immutables-dynamodb-mapper-poc.log
  level:
    com.github.simy4.poc: DEBUG
    org.springframework: WARN

springdoc:
  packages-to-scan: com.github.simy4.poc.controllers
  swagger-ui.path: /

management.server.port: 9001

db.entities.table-name: ${ENTITIES_TABLE:entities-table}

---
spring.config.activate.on-profile: local

spring.cloud.aws:
  dynamodb.endpoint: http://localhost:4566
  region.static: us-east-1
  credentials:
    access-key: test
    secret-key: test
