package com.github.simy4.poc.model;

import org.immutables.value.Value;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedUuid;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbFlatten;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbIgnore;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbImmutable;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

@Value.Style(
    jdkOnly = true,
    from = "",
    defaults = @Value.Immutable(copy = false),
    builtinContainerAttributes = false,
    get = {"get*", "is*"},
    passAnnotations = {
      DynamoDbAttribute.class,
      DynamoDbVersionAttribute.class,
      DynamoDbAutoGeneratedTimestampAttribute.class,
      DynamoDbAutoGeneratedUuid.class,
      DynamoDbFlatten.class,
      DynamoDbIgnore.class,
      DynamoDbImmutable.class,
      DynamoDbPartitionKey.class,
      DynamoDbSortKey.class,
    })
public @interface Data {}
