package com.github.simy4.poc.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.immutables.value.Value;
import org.jspecify.annotations.Nullable;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbIgnore;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbImmutable;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;
import tools.jackson.databind.annotation.JsonDeserialize;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Data
@Value.Immutable
@JsonDeserialize(as = ImmutableEntity.class)
@DynamoDbImmutable(builder = ImmutableEntity.Builder.class)
public abstract class Entity {
  public static final String PK_PREFIX = "Entity#";

  public static Identity id(String pk, String sk) {
    return new Identity(PK_PREFIX + pk, sk);
  }

  @JsonIgnore
  @DynamoDbIgnore
  public Identity getId() {
    return id(getPk(), getSk());
  }

  public abstract String getTenant();

  public abstract String getName();

  public abstract Address getAddress();

  public abstract List<Email> getEmails();

  public abstract Status getStatus();

  @Value.Default
  @JsonIgnore
  @DynamoDbPartitionKey
  public String getPk() {
    return PK_PREFIX + getTenant();
  }

  @Value.Default
  @DynamoDbSortKey
  @JsonProperty("id")
  public String getSk() {
    return UUID.randomUUID().toString();
  }

  @DynamoDbAutoGeneratedTimestampAttribute
  @Nullable public abstract Instant getUpdated();

  @Value.Default
  public Instant getCreated() {
    return Instant.now();
  }

  @DynamoDbVersionAttribute
  @Nullable @JsonIgnore
  public abstract Long getVersion();

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null || getClass() != obj.getClass()) {
      return false;
    }
    Entity entity = (Entity) obj;
    return getId().equals(entity.getId());
  }

  @Override
  public int hashCode() {
    return getId().hashCode();
  }
}
